# Example
master_ent 0xfe8f0000, 0x400000, 0, 0, 44, 1, type1_data, "/run/user/1000/u-relay-tproxy/A_#//2_"
master_ent ipv6_prefix_hi, ipv6_prefix_lo, 0, 0, 64, 3, type3_data, 0xfe800000, 0, 0, 0, "wlp3s0", 0, 0, 0, 0, 0
master_ent ipv6_prefix_hi, ipv6_prefix_lo+1, 0, 0, 64, 3, type3_data, 0xfe800000, 0, 0, 0, "enp3s0", 0, 0, 0, 0, 0
master_ent ipv6_prefix_hi, ipv6_prefix_lo+2, 0, 0, 64, 3, type3_data, 0xfe800000, 0, 0, 0, "eth0", 0, 0, 0, 0, 0
master_ent ipv6_prefix_hi, ipv6_prefix_lo+3, 0, 0, 64, 3, type3_data, 0xfe800000, 0, 0, 0, "eth1", 0, 0, 0, 0, 0
master_ent ipv6_prefix_hi, ipv6_prefix_lo+4, 0, 0, 64, 3, type3_data, 0xfe800000, 0, 0, 0, "wlan0", 0, 0, 0, 0, 0
master_ent ipv6_prefix_hi, ipv6_prefix_lo+5, 0, 0, 64, 3, type3_data, 0xfe800000, 0, 0, 0, "wlan1", 0, 0, 0, 0, 0
